WEATHER_CODES = {
    0: "Açık hava",
    1: "Az bulutlu",
    2: "Parçalı bulutlu",
    3: "Kapalı",
    45: "Sis",
    48: "Kırağılı sis",
    51: "Hafif çiseleme",
    53: "Orta çiseleme",
    55: "Yoğun çiseleme",
    56: "Hafif dondurucu çiseleme",
    57: "Yoğun dondurucu çiseleme",
    61: "Hafif yağmur",
    63: "Orta yağmur",
    65: "Şiddetli yağmur",
    66: "Hafif dondurucu yağmur",
    67: "Şiddetli dondurucu yağmur",
    71: "Hafif kar yağışı",
    73: "Orta kar yağışı",
    75: "Şiddetli kar yağışı",
    77: "Kar taneleri",
    80: "Hafif sağanak yağmur",
    81: "Orta sağanak yağmur",
    82: "Şiddetli sağanak yağmur",
    85: "Hafif kar sağanağı",
    86: "Şiddetli kar sağanağı",
    95: "Hafif veya orta gök gürültülü fırtına",
    96: "Hafif dolulu gök gürültülü fırtına",
    99: "Şiddetli dolulu gök gürültülü fırtına"
}
